from database import Database

a = {'ticket_purchase::id': None, 'ticket_purchase::number_of_kids': None, 'ticket_purchase::number_of_tickets': None, 'ticket_purchase::customer_name': None, 'ticket_purchase::fk_screening': None, 'screening::id': None, 'screening::time': None, 'screening::date': 'November 11', 'screening::price': None, 'screening::room': None, 'screening::fk_movie': None, 'screening::fk_theater': None, 'movie::id': None, 'movie::title': None, 'movie::genre': None, 'movie::director': 'Terry Gilliam', 'movie::plot': None, 'movie::actor': None, 'movie::rating': None, 'movie::cast': None, 'theater::id': None, 'theater::name': None, 'theater::chain': None, 'theater::city': None, 'theater::address': None}
b = {'ticket_purchase::id': None, 'ticket_purchase::number_of_kids': None, 'ticket_purchase::number_of_tickets': None, 'ticket_purchase::customer_name': None, 'ticket_purchase::fk_screening': None, 'screening::id': None, 'screening::time': None, 'screening::date': 'November 11', 'screening::price': None, 'screening::room': None, 'screening::fk_movie': None, 'screening::fk_theater': None, 'movie::id': 104, 'movie::title': 'Monty Python and the Holy Grail', 'movie::genre': 'Adventure', 'movie::director': 'Terry Gilliam', 
'movie::plot': 'History is turned on its comic head when, in 10th century England, King Arthur travels the countryside to find knights who will join him at the Round Table in Camelot. Gathering up the men is a tale in itself but after a bit of a party at Camelot, many decide to leave only to be stopped by God who sends them on a quest: to find the Holy Grail. After a series of individual adventures, the knights are reunited but must face a wizard named Tim, killer rabbits and lessons in the use of holy hand grenades. Their quest comes to an end however when the police intervene - just what you would expect in a Monty Python movie.', 
'movie::actor': 'Graham Chapman', 'movie::rating': 'pg', 'movie::cast': 'graham chapman, john cleese, eric idle, derry gilliam, terry jones', 'theater::id': None, 'theater::name': None, 'theater::chain': None, 'theater::city': None, 'theater::address': None}

db = Database.get_instance("mysql://root:toor@localhost:3306/movies")
db.build_knowledge_base([["ticket_purchase", "movie", "theater", "screening"]])
print(db.kb_lookup("movie", b))